---
title: Taylor Beseda
baseURL: "/"
params:
  header:
    title_url: "#"
    subtitle: "Nibh sed aliquam, cursus arcu aliquet  \nnatoque rhoncus ut non in
      Aliquet"
    actions:
    - label: Download
      icon: fa-download
      url: elements.md
      is_primary: true
      is_scrolly: false
    - label: Learn More
      icon: fa-chevron-down
      url: "#one"
      is_primary: false
      is_scrolly: true
    img:
      path: images/screen.jpg
      phone_border: true
  palette: blue
  palettes:
    blue:
      sass:
        color: "#4696e5"
    magenta:
      sass:
        color: "#db5c7a"
    purple:
      sass:
        color: "#786dc2"
  footer:
    social_icons:
    - title: Facebook
      icon: fa-facebook
      url: "#"
    - title: Twitter
      icon: fa-twitter
      url: "#"
    - title: Instagram
      icon: fa-instagram
      url: "#"
    copyright: "&copy; Untitled."
disableKinds:
- RSS
